---
title: "Skills-for-care analysis ARNOVA 2023"
author: "Meng Ye"
date: "2024-03-01"
output:
  word_document: default
  html_document: default
---

```{r contr}
# environment setup to run ordered logit properly
options(contrasts = rep("contr.treatment", 2))
```


This chunk loads all the packages to use

```{r load package, message=FALSE, warning=FALSE}
#packages for ordered logit
library(tidyverse) # package for data cleaning and plotting
library(readxl) # package for reading excel file
library(broom) # extracting model summary as data frame
library(modelsummary) # deriving model tables
library(scales) # label percent
library(lubridate) # working with dates
library(marginaleffects) #to calculate marginal effects
library(ordinal) # package for ordinal logit regression
library(here) # specifying directory 
```



## Data Preparation

First, import the sampled and coded data set

```{r import data, message=FALSE, warning=FALSE}
#import the raw data file
cqc_skills <- read_rds(here("data","cleaned_sfc_ipw.rds")) 

```






## Modeling on rating with staff control

```{r }
model_order <- clm(rating ~ form  + category + region + during_covid,
                data = filter(cqc_skills, domain == "Overall"),
                link = "logit")

model_order_weighted <- clm(rating ~ form + category + region + during_covid,
                data = filter(cqc_skills, domain == "Overall"),
                link = "logit",
                weights = ipw)

model_order_weighted2 <- clm(rating ~ form + category + region + during_covid,
                data = filter(cqc_skills, domain == "Overall"),
                link = "logit",
                weights = ipw_short)


model_staff <- lm(staff_level ~ form + category + region + during_covid,
                data = filter(cqc_skills, domain == "Overall"))

model_staff_weighted <- lm(staff_level ~ form + category + region + during_covid,
                data = filter(cqc_skills, domain == "Overall"),
                weights = ipw)

staff_direct_order <- clm(rating ~ form + staff_level + category + region + during_covid,
                data = filter(cqc_skills, domain == "Overall"),
                link = "logit")
staff_direct_order_weighted <- clm(rating ~ form + staff_level + category + region + during_covid,
                data = filter(cqc_skills, domain == "Overall"),
                link = "logit",
                weights = ipw)
```




```{r}
staff_models <- modelsummary(list("full" = model_order, "full weighted" = model_order_weighted, 
                                  "full weighted 2" = model_order_weighted2, 
                                    "staffing" = model_staff, "staffing weighted"= model_staff_weighted, 
                                    "direct" = staff_direct_order, "direct weighted" = staff_direct_order_weighted),
                               coef_omit = "region", exponentiate = F,
                               statistic = "({p.value}) {stars}")
staff_models
```

# Modeling on rating with turnover

```{r }

model_turnover <- lm(turnover ~ form + category + region + during_covid,
                data = filter(cqc_skills, domain == "Overall"))

model_turnover_weighted <- lm(turnover ~ form + category + region + during_covid,
                data = filter(cqc_skills, domain == "Overall"),
                weights = ipw)

turnover_direct_order <- clm(rating ~ form + turnover + category + region + during_covid,
                data = filter(cqc_skills, domain == "Overall"),
                link = "logit")
turnover_direct_order_weighted <- clm(rating ~ form + turnover + category + region + during_covid,
                data = filter(cqc_skills, domain == "Overall"),
                link = "logit",
                weights = ipw)
```




```{r}
staff_models <- modelsummary(list("full" = model_order, "full weighted" = model_order_weighted, 
                                    "turnover" = model_turnover, "turnover weighted"= model_turnover_weighted, 
                                    "direct" = turnover_direct_order, "direct weighted" = turnover_direct_order_weighted),
                               coef_omit = "region", exponentiate = F,
                               statistic = "({p.value}) {stars}")
staff_models
```
